esphome:
  name: esp32c6-nodo2
  friendly_name: Nodo 2 ESP32-C6

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf

wifi:
  ssid:  "OPPO A58"
  password: "LisyandFeli2004:)"
  power_save_mode: none

logger:

ota:
  platform: esphome

api:

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

# =====================
#   S E N S O R E S
# =====================
sensor:
  # --- DHT11 ---
  - platform: dht
    pin: GPIO4
    model: DHT11
    temperature:
      name: "Nodo 2 Temperatura"
      id: nodo2_temp
      filters:
        - offset: 1.0
    humidity:
      name: "Nodo 2 Humedad"
      id: nodo2_hum
      filters:
        - offset: -3.0
    update_interval: 10s

  # --- BME280 ---

  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperatura"
    pressure:
      name: "BME280 Presion"
    humidity:
      name: "BME280 Humedad"
    address: 0x76
    update_interval: 10s

  # --- LDR ---
  #- platform: adc
  #  pin: GPIO3
  #  name: "Nodo 2 Luminosidad"
  #  id: nodo2_luz
  #  attenuation: 12db
  #  update_interval: 5s
  #  filters:
   #   - multiply: 1000

  # --- MQ135 EN GPIO2 ---
  #- platform: adc
  #  pin: GPIO2
  #  id: gas_raw
   # name: "Nodo 2 MQ135 (valor bruto)"
   # attenuation: 12db
   # update_interval: 3s



